default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "example") %>
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: freight_train_development

test:
  <<: *default
  database: freight_train_test

production:
  database: freight_train_production
  url: <%= ENV.fetch("DATABASE_URL", "example") %>
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  
